[project]
authors = ["ZHU Yuhao 朱宇浩 <dr.yuhao.zhu@outlook.com>"]
channels = ["https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
# channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
description = "A comprehensive decimal and integer mathematics library for Mojo"
license = "Apache-2.0"
name = "decimojo"
platforms = ["osx-arm64", "linux-64"]
readme = "README.md"
version = "0.2.0"

[dependencies]
max = ">=25.2"

[tasks]
# format the code
format = "magic run mojo format ./"

# compile the package
package_decimojo = "magic run mojo package src/decimojo && cp decimojo.mojopkg tests/ && cp decimojo.mojopkg benches/ && rm decimojo.mojopkg"
package_tomlmojo = "magic run mojo package src/tomlmojo && mv tomlmojo.mojopkg tests/"
package = "magic run format && magic run package_decimojo && magic run package_tomlmojo"
p = "clear && magic run package"

# clean the package files in tests folder
clean = "rm tests/decimojo.mojopkg && rm benches/decimojo.mojopkg && rm tests/tomlmojo.mojopkg"
c = "clear && magic run clean"

# tests (use the mojo testing tool)
test = "magic run package && magic run mojo test tests --filter"
t = "clear && magic run package && magic run mojo test tests --filter"

# benches
bench_decimal = "clear && magic run package && cd benches/decimal && magic run mojo -I ../ bench.mojo && cd ../.. && magic run clean"
bench_bigint = "clear && magic run package && cd benches/bigint && magic run mojo -I ../ bench.mojo && cd ../.. && magic run clean"
bench_biguint = "clear && magic run package && cd benches/biguint && magic run mojo -I ../ bench.mojo && cd ../.. && magic run clean"
bench_bigdecimal = "clear && magic run package && cd benches/bigdecimal && magic run mojo -I ../ bench.mojo && cd ../.. && magic run clean"
bench_dec = "magic run bench_decimal"
bench_bint = "magic run bench_bigint"
bench_buint = "magic run bench_biguint"
bench_bdec = "magic run bench_bigdecimal"
