[project]
authors = ["ZHU Yuhao 朱宇浩 <dr.yuhao.zhu@outlook.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
description = "A fixed-point decimal arithmetic library written in Mojo 🔥"
license = "Apache-2.0"
name = "decimojo"
platforms = ["osx-arm64", "linux-64"]
readme = "README.md"
version = "0.1.0"

[dependencies]
max = ">=25.1,<25.3"

[tasks]
# format the code
format = "magic run mojo format ./"

# compile the package
package = "magic run format && magic run mojo package src/decimojo && cp decimojo.mojopkg tests/ && cp decimojo.mojopkg benches/ && rm decimojo.mojopkg"
p = "clear && magic run package"

# clean the package files in tests folder
clean = "rm tests/decimojo.mojopkg && rm benches/decimojo.mojopkg"

# tests (use the mojo testing tool)
test = "magic run package && magic run mojo test tests --filter"
t = "clear && magic run package && magic run mojo test tests --filter"

# benches
bench = "magic run package && cd benches && magic run mojo bench.mojo && cd .. && magic run clean"
b = "clear && magic run bench"
bench_multiply = "magic run package && cd benches && magic run mojo bench_multiply.mojo && cd .. && magic run clean"
bench_divide = "magic run package && cd benches && magic run mojo bench_divide.mojo && cd .. && magic run clean"
bench_floor_divide = "magic run package && cd benches && magic run mojo bench_floor_divide.mojo && cd .. && magic run clean"
bench_modulo = "magic run package && cd benches && magic run mojo bench_modulo.mojo && cd .. && magic run clean"
bench_sqrt = "magic run package && cd benches && magic run mojo bench_sqrt.mojo && cd .. && magic run clean"
bench_root = "magic run package && cd benches && magic run mojo bench_root.mojo && cd .. && magic run clean"
bench_round = "magic run package && cd benches && magic run mojo bench_round.mojo && cd .. && magic run clean"
bench_quantize = "magic run package && cd benches && magic run mojo bench_quantize.mojo && cd .. && magic run clean"
bench_from_float = "magic run package && cd benches && magic run mojo bench_from_float.mojo && cd .. && magic run clean"
bench_from_string = "magic run package && cd benches && magic run mojo bench_from_string.mojo && cd .. && magic run clean"
bench_from_int = "magic run package && cd benches && magic run mojo bench_from_int.mojo && cd .. && magic run clean"
bench_comparison = "magic run package && cd benches && magic run mojo bench_comparison.mojo && cd .. && magic run clean"
bench_exp = "magic run package && cd benches && magic run mojo bench_exp.mojo && cd .. && magic run clean"
bench_ln = "magic run package && cd benches && magic run mojo bench_ln.mojo && cd .. && magic run clean"
bench_log10 = "magic run package && cd benches && magic run mojo bench_log10.mojo && cd .. && magic run clean"
bench_power = "magic run package && cd benches && magic run mojo bench_power.mojo && cd .. && magic run clean"
