[project]
authors = ["ZHU Yuhao 朱宇浩 <dr.yuhao.zhu@outlook.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
description = "A fixed-point decimal arithmetic library written in Mojo 🔥"
license = "Apache-2.0"
name = "decimal"
platforms = ["osx-arm64", "linux-64"]
readme = "README.md"
version = "0.1.0"

[tasks]
# format the code
format = "magic run mojo format ./"

# compile the package
package = "magic run format && magic run mojo package decimojo && cp decimojo.mojopkg ./tests/ && cp decimojo.mojopkg ./benches/ && rm decimojo.mojopkg"
p = "clear && magic run package"

# debugs (run the testing files only)
debug = "magic run package && magic run mojo tests/*.mojo"
d = "clear && magic run debug"

# tests (use the mojo testing tool)
test = "magic run package && magic run mojo test tests"
t = "clear && magic run test"

# benches
bench = "magic run package && cd benches && magic run mojo bench.mojo && cd .."
b = "clear && magic run bench"

# before commit
final = "magic run test && magic run bench"
f = "clear && magic run final"

[dependencies]
max = ">=25.1,<25.3"
