[project]
authors = ["ZHU Yuhao 朱宇浩 <dr.yuhao.zhu@outlook.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
description = "A fixed-point decimal arithmetic library written in Mojo 🔥"
license = "Apache-2.0"
name = "decimojo"
platforms = ["osx-arm64", "linux-64"]
readme = "README.md"
version = "0.1.0"

[dependencies]
max = ">=25.1,<25.3"

[tasks]
# format the code
format = "magic run mojo format ./"

# compile the package
package = "magic run format && magic run mojo package src/decimojo && cp decimojo.mojopkg tests/ && cp decimojo.mojopkg benches/ && rm decimojo.mojopkg"
p = "clear && magic run package"

# delete the package files in tests folder
delete_package = "rm tests/decimojo.mojopkg && rm benches/decimojo.mojopkg"

# debugs (run the testing files only)
debug = "magic run package && magic run mojo tests/*.mojo && magic run delete_package"
debug_arith = "magic run package && magic run mojo tests/test_arithmetics.mojo && magic run delete_package"
debug_div = "magic run package && magic run mojo tests/test_division.mojo && magic run delete_package"
debug_sqrt = "magic run package && magic run mojo tests/test_sqrt.mojo && magic run delete_package"

# tests (use the mojo testing tool)
test = "magic run package && magic run mojo test tests && magic run delete_package"
t = "clear && magic run test"
test_arith = "magic run package && magic run mojo test tests/test_arithmetics.mojo && magic run delete_package"
test_multiply = "magic run package && magic run mojo test tests/test_multiply.mojo && magic run delete_package"
test_divide = "magic run package && magic run mojo test tests/test_divide.mojo && magic run delete_package"
test_sqrt = "magic run package && magic run mojo test tests/test_sqrt.mojo && magic run delete_package"
test_root = "magic run package && magic run mojo test tests/test_root.mojo && magic run delete_package"
test_round = "magic run package && magic run mojo test tests/test_round.mojo && magic run delete_package"
test_quantize  = "magic run package && magic run mojo test tests/test_quantize.mojo && magic run delete_package"
test_from_components = "magic run package && magic run mojo test tests/test_from_components.mojo && magic run delete_package"
test_from_float = "magic run package && magic run mojo test tests/test_from_float.mojo && magic run delete_package"
test_from_string = "magic run package && magic run mojo test tests/test_from_string.mojo && magic run delete_package"
test_from_int = "magic run package && magic run mojo test tests/test_from_int.mojo && magic run delete_package"
test_to_float = "magic run package && magic run mojo test tests/test_to_float.mojo && magic run delete_package"
test_comparison = "magic run package && magic run mojo test tests/test_comparison.mojo && magic run delete_package"
test_factorial = "magic run package && magic run mojo test tests/test_factorial.mojo && magic run delete_package"
test_exp = "magic run package && magic run mojo test tests/test_exp.mojo && magic run delete_package"
test_ln = "magic run package && magic run mojo test tests/test_ln.mojo && magic run delete_package"
test_log  = "magic run package && magic run mojo test tests/test_log.mojo && magic run delete_package"
test_log10  = "magic run package && magic run mojo test tests/test_log10.mojo && magic run delete_package"
test_power = "magic run package && magic run mojo test tests/test_power.mojo && magic run delete_package"

# benches
bench = "magic run package && cd benches && magic run mojo bench.mojo && cd .. && magic run delete_package"
b = "clear && magic run bench"
bench_multiply = "magic run package && cd benches && magic run mojo bench_multiply.mojo && cd .. && magic run delete_package"
bench_divide = "magic run package && cd benches && magic run mojo bench_divide.mojo && cd .. && magic run delete_package"
bench_sqrt = "magic run package && cd benches && magic run mojo bench_sqrt.mojo && cd .. && magic run delete_package"
bench_root = "magic run package && cd benches && magic run mojo bench_root.mojo && cd .. && magic run delete_package"
bench_round = "magic run package && cd benches && magic run mojo bench_round.mojo && cd .. && magic run delete_package"
bench_quantize = "magic run package && cd benches && magic run mojo bench_quantize.mojo && cd .. && magic run delete_package"
bench_from_float = "magic run package && cd benches && magic run mojo bench_from_float.mojo && cd .. && magic run delete_package"
bench_from_string = "magic run package && cd benches && magic run mojo bench_from_string.mojo && cd .. && magic run delete_package"
bench_from_int = "magic run package && cd benches && magic run mojo bench_from_int.mojo && cd .. && magic run delete_package"
bench_comparison = "magic run package && cd benches && magic run mojo bench_comparison.mojo && cd .. && magic run delete_package"
bench_exp = "magic run package && cd benches && magic run mojo bench_exp.mojo && cd .. && magic run delete_package"
bench_ln = "magic run package && cd benches && magic run mojo bench_ln.mojo && cd .. && magic run delete_package"
bench_log10 = "magic run package && cd benches && magic run mojo bench_log10.mojo && cd .. && magic run delete_package"
bench_power = "magic run package && cd benches && magic run mojo bench_power.mojo && cd .. && magic run delete_package"
