"""Type stubs for the _decimo Mojo extension module.

This file tells Pylance/mypy the interface of the compiled _decimo.so.
"""

class BigDecimal:
    def __init__(self, value: str) -> None: ...
    def to_string(self) -> str: ...
    def to_repr(self) -> str: ...
    def add(self, other: BigDecimal) -> BigDecimal: ...
    def sub(self, other: BigDecimal) -> BigDecimal: ...
    def mul(self, other: BigDecimal) -> BigDecimal: ...
    def div(self, other: BigDecimal) -> BigDecimal: ...
    def neg(self) -> BigDecimal: ...
    def abs_(self) -> BigDecimal: ...
    def eq(self, other: BigDecimal) -> bool: ...
    def lt(self, other: BigDecimal) -> bool: ...
    def le(self, other: BigDecimal) -> bool: ...
